spring.mongodb.database=electromart
spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
spring.servlet.multipart.max-file-size=10MB
cloudinary.cloud-name=dzrjq4von
cloudinary.api-key=716664757213899
cloudinary.api-secret=yPJKYREUGUy6sf99wenbApNpTJw
app.cors.allowed-origins=http://localhost:4200
app.cors.allowed-origins=https://megaecommercw.vercel.app/
app.cors.allowed-origins=https://megaecommercw.vercel.app
app.cors.allowed-origins=https://www.megaecommerce.store
app.cors.allowed-origins=https://www.megaecomm.store
